/*
 * SoundCloud Public API Specification
 *
 * Swagger json can be found [here](https://developers.soundcloud.com/docs/api/explorer/api.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MeLikesPlaylistsGet200Response {
    Playlists(Box<models::Playlists>),
    PlaylistsArray(Vec<models::Playlist>),
}

impl Default for MeLikesPlaylistsGet200Response {
    fn default() -> Self {
        Self::Playlists(Default::default())
    }
}

