/*
 * SoundCloud Public API Specification
 *
 * Swagger json can be found [here](https://developers.soundcloud.com/docs/api/explorer/api.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TracksTrackIdCommentsPostRequestCommentTimestamp : Timestamp of a comment. String or float representation is supported
/// Timestamp of a comment. String or float representation is supported
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TracksTrackIdCommentsPostRequestCommentTimestamp {
    String(String),
    Number(f64),
}

impl Default for TracksTrackIdCommentsPostRequestCommentTimestamp {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

