/*
 * SoundCloud Public API Specification
 *
 * Swagger json can be found [here](https://developers.soundcloud.com/docs/api/explorer/api.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TracksTrackIdCommentsPostRequestComment {
    /// Comment's content
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Box<models::TracksTrackIdCommentsPostRequestCommentTimestamp>>,
}

impl TracksTrackIdCommentsPostRequestComment {
    pub fn new(body: String) -> TracksTrackIdCommentsPostRequestComment {
        TracksTrackIdCommentsPostRequestComment {
            body,
            timestamp: None,
        }
    }
}

