/*
 * SoundCloud Public API Specification
 *
 * Swagger json can be found [here](https://developers.soundcloud.com/docs/api/explorer/api.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TracksGetCreatedAtParameter {
    /// (yyyy-mm-dd hh:mm:ss) return tracks created at this date or later
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// (yyyy-mm-dd hh:mm:ss) return tracks created at this date or earlier
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
}

impl TracksGetCreatedAtParameter {
    pub fn new() -> TracksGetCreatedAtParameter {
        TracksGetCreatedAtParameter {
            from: None,
            to: None,
        }
    }
}

