/*
 * SoundCloud Public API Specification
 *
 * Swagger json can be found [here](https://developers.soundcloud.com/docs/api/explorer/api.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Activities : User's activities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Activities {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::ActivitiesItemsInner>>,
    #[serde(rename = "next_href", skip_serializing_if = "Option::is_none")]
    pub next_href: Option<String>,
    #[serde(rename = "future_href", skip_serializing_if = "Option::is_none")]
    pub future_href: Option<String>,
}

impl Activities {
    /// User's activities.
    pub fn new() -> Activities {
        Activities {
            items: None,
            next_href: None,
            future_href: None,
        }
    }
}

