/*
 * SoundCloud Public API Specification
 *
 * Swagger json can be found [here](https://developers.soundcloud.com/docs/api/explorer/api.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUpdatePlaylistRequest {
    #[serde(rename = "playlist", skip_serializing_if = "Option::is_none")]
    pub playlist: Option<Box<models::CreateUpdatePlaylistRequestPlaylist>>,
}

impl CreateUpdatePlaylistRequest {
    pub fn new() -> CreateUpdatePlaylistRequest {
        CreateUpdatePlaylistRequest {
            playlist: None,
        }
    }
}

