/*
 * SoundCloud Public API Specification
 *
 * Swagger json can be found [here](https://developers.soundcloud.com/docs/api/explorer/api.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeQuota : user's upload quota
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeQuota {
    /// unlimited upload quota.
    #[serde(rename = "unlimited_upload_quota", skip_serializing_if = "Option::is_none")]
    pub unlimited_upload_quota: Option<bool>,
    /// upload seconds used.
    #[serde(rename = "upload_seconds_used", skip_serializing_if = "Option::is_none")]
    pub upload_seconds_used: Option<i32>,
    /// upload seconds left.
    #[serde(rename = "upload_seconds_left", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub upload_seconds_left: Option<Option<i32>>,
}

impl MeQuota {
    /// user's upload quota
    pub fn new() -> MeQuota {
        MeQuota {
            unlimited_upload_quota: None,
            upload_seconds_used: None,
            upload_seconds_left: None,
        }
    }
}

