/*
 * SoundCloud Public API Specification
 *
 * Swagger json can be found [here](https://developers.soundcloud.com/docs/api/explorer/api.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeSubscriptionsInner {
    #[serde(rename = "product", skip_serializing_if = "Option::is_none")]
    pub product: Option<Box<models::UserSubscriptionsInnerAnyOfProduct>>,
    /// if the subscription is recurring or not
    #[serde(rename = "recurring", skip_serializing_if = "Option::is_none")]
    pub recurring: Option<bool>,
}

impl MeSubscriptionsInner {
    pub fn new() -> MeSubscriptionsInner {
        MeSubscriptionsInner {
            product: None,
            recurring: None,
        }
    }
}

