/*
 * SoundCloud Public API Specification
 *
 * Swagger json can be found [here](https://developers.soundcloud.com/docs/api/explorer/api.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Playlist : Soundcloud Playlist Object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Playlist {
    /// Playlist title.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Playlist identifier.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Type of Soundcloud object (playlist).
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// URL to a JPEG image.
    #[serde(rename = "artwork_url", skip_serializing_if = "Option::is_none")]
    pub artwork_url: Option<String>,
    /// Created timestamp.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Playlist description.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// is downloadable.
    #[serde(rename = "downloadable", skip_serializing_if = "Option::is_none")]
    pub downloadable: Option<bool>,
    /// Playlist duration.
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    /// European Article Number.
    #[serde(rename = "ean", skip_serializing_if = "Option::is_none")]
    pub ean: Option<String>,
    /// Embeddable by.
    #[serde(rename = "embeddable_by", skip_serializing_if = "Option::is_none")]
    pub embeddable_by: Option<String>,
    /// Playlist genre.
    #[serde(rename = "genre", skip_serializing_if = "Option::is_none")]
    pub genre: Option<String>,
    /// Label user identifier.
    #[serde(rename = "label_id", skip_serializing_if = "Option::is_none")]
    pub label_id: Option<i32>,
    /// Label name.
    #[serde(rename = "label_name", skip_serializing_if = "Option::is_none")]
    pub label_name: Option<String>,
    /// Last modified timestamp.
    #[serde(rename = "last_modified", skip_serializing_if = "Option::is_none")]
    pub last_modified: Option<String>,
    /// License.
    #[serde(rename = "license", skip_serializing_if = "Option::is_none")]
    pub license: Option<String>,
    /// Playlist permalink.
    #[serde(rename = "permalink", skip_serializing_if = "Option::is_none")]
    pub permalink: Option<String>,
    /// Playlist permalink URL.
    #[serde(rename = "permalink_url", skip_serializing_if = "Option::is_none")]
    pub permalink_url: Option<String>,
    /// Type of playlist.
    #[serde(rename = "playlist_type", skip_serializing_if = "Option::is_none")]
    pub playlist_type: Option<String>,
    /// Purchase title.
    #[serde(rename = "purchase_title", skip_serializing_if = "Option::is_none")]
    pub purchase_title: Option<String>,
    /// Purchase URL.
    #[serde(rename = "purchase_url", skip_serializing_if = "Option::is_none")]
    pub purchase_url: Option<String>,
    /// Release.
    #[serde(rename = "release", skip_serializing_if = "Option::is_none")]
    pub release: Option<String>,
    /// Day of release.
    #[serde(rename = "release_day", skip_serializing_if = "Option::is_none")]
    pub release_day: Option<i32>,
    /// Month of release.
    #[serde(rename = "release_month", skip_serializing_if = "Option::is_none")]
    pub release_month: Option<i32>,
    /// Year of release.
    #[serde(rename = "release_year", skip_serializing_if = "Option::is_none")]
    pub release_year: Option<i32>,
    /// Type of sharing (private/public).
    #[serde(rename = "sharing", skip_serializing_if = "Option::is_none")]
    pub sharing: Option<String>,
    /// Is streamable.
    #[serde(rename = "streamable", skip_serializing_if = "Option::is_none")]
    pub streamable: Option<bool>,
    /// Tags.
    #[serde(rename = "tag_list", skip_serializing_if = "Option::is_none")]
    pub tag_list: Option<String>,
    /// Count of tracks.
    #[serde(rename = "track_count", skip_serializing_if = "Option::is_none")]
    pub track_count: Option<i32>,
    /// List of tracks.
    #[serde(rename = "tracks", skip_serializing_if = "Option::is_none")]
    pub tracks: Option<Vec<models::Track>>,
    /// Playlist type.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Playlist URI.
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    #[serde(rename = "user", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user: Option<Option<Box<models::User>>>,
    /// User identifier.
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// Count of playlist likes.
    #[serde(rename = "likes_count", skip_serializing_if = "Option::is_none")]
    pub likes_count: Option<i32>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Box<models::PlaylistLabel>>,
    /// tracks URI.
    #[serde(rename = "tracks_uri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tracks_uri: Option<Option<String>>,
    /// Tags.
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<String>>,
}

impl Playlist {
    /// Soundcloud Playlist Object
    pub fn new() -> Playlist {
        Playlist {
            title: None,
            id: None,
            kind: None,
            artwork_url: None,
            created_at: None,
            description: None,
            downloadable: None,
            duration: None,
            ean: None,
            embeddable_by: None,
            genre: None,
            label_id: None,
            label_name: None,
            last_modified: None,
            license: None,
            permalink: None,
            permalink_url: None,
            playlist_type: None,
            purchase_title: None,
            purchase_url: None,
            release: None,
            release_day: None,
            release_month: None,
            release_year: None,
            sharing: None,
            streamable: None,
            tag_list: None,
            track_count: None,
            tracks: None,
            r#type: None,
            uri: None,
            user: None,
            user_id: None,
            likes_count: None,
            label: None,
            tracks_uri: None,
            tags: None,
        }
    }
}

