/*
 * SoundCloud Public API Specification
 *
 * Swagger json can be found [here](https://developers.soundcloud.com/docs/api/explorer/api.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Streams {
    #[serde(rename = "http_mp3_128_url", skip_serializing_if = "Option::is_none")]
    pub http_mp3_128_url: Option<String>,
    #[serde(rename = "hls_mp3_128_url", skip_serializing_if = "Option::is_none")]
    pub hls_mp3_128_url: Option<String>,
    #[serde(rename = "hls_opus_64_url", skip_serializing_if = "Option::is_none")]
    pub hls_opus_64_url: Option<String>,
    #[serde(rename = "preview_mp3_128_url", skip_serializing_if = "Option::is_none")]
    pub preview_mp3_128_url: Option<String>,
}

impl Streams {
    pub fn new() -> Streams {
        Streams {
            http_mp3_128_url: None,
            hls_mp3_128_url: None,
            hls_opus_64_url: None,
            preview_mp3_128_url: None,
        }
    }
}

