/*
 * SoundCloud Public API Specification
 *
 * Swagger json can be found [here](https://developers.soundcloud.com/docs/api/explorer/api.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSubscriptionsInner {
    #[serde(rename = "anyOf", skip_serializing_if = "Option::is_none")]
    pub any_of: Option<Box<models::UserSubscriptionsInnerAnyOf>>,
}

impl UserSubscriptionsInner {
    pub fn new() -> UserSubscriptionsInner {
        UserSubscriptionsInner {
            any_of: None,
        }
    }
}

