/*
 * SoundCloud Public API Specification
 *
 * Swagger json can be found [here](https://developers.soundcloud.com/docs/api/explorer/api.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserSubscriptionsInnerAnyOfProduct : product
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSubscriptionsInnerAnyOfProduct {
    /// subscription id instance.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// subscription name instance.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl UserSubscriptionsInnerAnyOfProduct {
    /// product
    pub fn new() -> UserSubscriptionsInnerAnyOfProduct {
        UserSubscriptionsInnerAnyOfProduct {
            id: None,
            name: None,
        }
    }
}

